/**
 * This file was generated by the Jeddict
 */
package org.eethar.platform.core.entity;

import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author superyass
 */
@Entity
public class Donation implements IGenericEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String donerName;

    @Basic
    private String donerEmail;

    @Basic
    private Float donationAmount;

    @Basic
    private Float tipAmount;

    @Basic
    @Temporal(TemporalType.TIMESTAMP)
    private Date donationDate;

    @ElementCollection
    private List<String> donerType;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDonerName() {
        return this.donerName;
    }

    public void setDonerName(String donerName) {
        this.donerName = donerName;
    }

    public String getDonerEmail() {
        return this.donerEmail;
    }

    public void setDonerEmail(String donerEmail) {
        this.donerEmail = donerEmail;
    }

    public Float getDonationAmount() {
        return this.donationAmount;
    }

    public void setDonationAmount(Float donationAmount) {
        this.donationAmount = donationAmount;
    }

    public Float getTipAmount() {
        return this.tipAmount;
    }

    public void setTipAmount(Float tipAmount) {
        this.tipAmount = tipAmount;
    }

    public Date getDonationDate() {
        return this.donationDate;
    }

    public void setDonationDate(Date donationDate) {
        this.donationDate = donationDate;
    }

    public List<String> getDonerType() {
        return this.donerType;
    }

    public void setDonerType(List<String> donerType) {
        this.donerType = donerType;
    }

}
