/**
 * This file was generated by the Jeddict
 */
package org.eethar.platform.core.entity;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author superyass
 */
@Entity
public class NGO implements IGenericEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String name;

    @Basic
    private String description;

    @ElementCollection
    private List<String> ngoType;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getNgoType() {
        return this.ngoType;
    }

    public void setNgoType(List<String> ngoType) {
        this.ngoType = ngoType;
    }

}
